name: tpvformer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - pip:
      - addict==2.4.0
      - cachetools==5.5.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - descartes==1.1.0
      - fire==0.7.1
      - fonttools==4.57.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - llvmlite==0.31.0
      - matplotlib==3.5.3
      - mmcv-full==1.4.0
      - mmdet==2.14.0
      - mmsegmentation==0.14.1
      - numba==0.48.0
      - numpy==1.23.1
      - nuscenes-devkit==1.1.11
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==9.3.0
      - platformdirs==4.3.6
      - prettytable==3.11.0
      - pycocotools==2.0.7
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shapely==1.8.5.post1
      - six==1.17.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - timm==0.4.12
      - tomli==2.2.1
      - torch==1.10.0+cu113
      - torchvision==0.11.0+cu113
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - wcwidth==0.2.13
      - yapf==0.32.0
      - zipp==3.20.2
prefix: /home/h00323/miniconda3/envs/tpvformer
