name: occfrmwrk
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - blas=2.137=mkl
  - blas-devel=3.9.0=37_hcf00494_mkl
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cudatoolkit=11.6.2=hfc3e2af_13
  - debugpy=1.8.17=py310h25320af_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=37_h5875eb1_mkl
  - libcblas=3.9.0=37_hfef963f_mkl
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=37_h5e43f62_mkl
  - liblapacke=3.9.0=37_hdba1596_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=21.1.5=h4922eb0_0
  - mkl=2024.2.2=ha770c72_17
  - mkl-devel=2024.2.2=ha770c72_17
  - mkl-include=2024.2.2=ha770c72_17
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - psutil=7.1.0=py310h7c4b9e2_0
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pytorch-mutex=1.0=cuda
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.12.1=py310_cu116
  - tornado=6.5.2=py310h7c4b9e2_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - asttokens==3.0.0
      - attrs==25.3.0
      - black==25.1.0
      - blinker==1.9.0
      - cachetools==6.1.0
      - ccimport==0.4.4
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - colorama==0.4.6
      - configargparse==1.7.1
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==45.0.6
      - cumm-cu124==0.7.11
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - descartes==1.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.20.0
      - fire==0.7.0
      - flake8==7.3.0
      - flask==3.1.1
      - fonttools==4.59.0
      - fsspec==2025.10.0
      - grpcio==1.74.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - imageio==2.37.0
      - iniconfig==2.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.3
      - model-index==0.1.11
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==2.1.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==1.26.4
      - nuscenes-devkit==1.1.11
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pccm==0.4.16
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.3.8
      - plotly==6.3.0
      - pluggy==1.6.0
      - plyfile==1.1.2
      - portalocker==3.2.0
      - prettytable==3.16.0
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pycocotools==2.0.10
      - pycodestyle==2.14.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pytest==8.4.1
      - pytz==2023.4
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.28.2
      - retrying==1.4.2
      - rich==13.4.2
      - rpds-py==0.27.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==1.8.5.post1
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.20
      - tomli==2.2.1
      - torch==2.4.0
      - torch-scatter==2.1.2+pt24cu124
      - torchvision==0.19.0
      - tqdm==4.65.2
      - trimesh==4.7.3
      - triton==3.0.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - yapf==0.43.0
prefix: /home/h00323/miniconda3/envs/occfrmwrk
